/**
 * API Route: Generate AI summaries for playoff scenarios
 *
 * POST /api/playoff-scenarios/summarize
 *
 * Takes standings, matchups, and scenarios data and returns
 * human-readable summaries generated by Gemini.
 */

import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { generateTeamScenarioSummary } from '@/features/playoffs/simulations/scenario-summarizer';
import { authorizeBearer, createFixedWindowGate, readBoundedBody } from '@/lib/api-security';

const MAX_REQUEST_BYTES = 48 * 1024;
const requestGate = createFixedWindowGate({ limit: 10, windowMs: 60_000 });
const shortText = z.string().trim().min(1).max(120);
const boundedNumber = z.number().finite().min(0).max(1_000_000);

const scenarioConditionSchema = z
  .object({
    type: z.enum(['win', 'lose', 'other_team_wins', 'other_team_loses', 'points_margin']),
    teamName: shortText,
    rosterId: z.number().int().min(1).max(10_000),
    marginRequired: z.number().finite().min(-1_000).max(1_000).optional(),
  })
  .strict();

const pathConditionSchema = z
  .object({
    type: z.enum(['win', 'lose', 'other_result', 'points_margin']),
    teamName: shortText,
    rosterId: z.number().int().min(1).max(10_000),
    opponentName: shortText.optional(),
    opponentRosterId: z.number().int().min(1).max(10_000).optional(),
    wins: z.boolean().optional(),
    marginRequired: z.number().finite().min(-1_000).max(1_000).optional(),
    vsTeamName: shortText.optional(),
  })
  .strict();

const seedPathSchema = z
  .object({
    outcomeId: z.number().int().min(0).max(1_000),
    conditions: z.array(pathConditionSchema).max(12),
  })
  .strict();

const pathSummarySchema = z
  .object({
    type: z.enum(['guaranteed', 'conditional', 'impossible']),
    requiresWin: z.boolean().nullable(),
    description: z.string().trim().min(1).max(500),
    additionalConditions: z.array(z.string().trim().min(1).max(200)).max(12).optional(),
    pathCount: z.number().int().min(0).max(1_000),
    winPathCount: z.number().int().min(0).max(1_000),
    losePathCount: z.number().int().min(0).max(1_000),
  })
  .strict();

const requestBodySchema = z
  .object({
    teamName: shortText,
    ownerName: shortText,
    currentRecord: z.string().trim().min(1).max(16),
    currentPoints: boundedNumber,
    division: z.number().int().min(1).max(12),
    scenarios: z
      .array(
        z
          .object({
            seed: z.number().int().min(1).max(12),
            probability: z.number().finite().min(0).max(1),
            conditions: z.array(scenarioConditionSchema).max(12),
            paths: z.array(seedPathSchema).max(64).optional(),
            summary: pathSummarySchema.optional(),
          })
          .strict(),
      )
      .min(1)
      .max(12),
    standings: z
      .array(
        z
          .object({
            rosterId: z.number().int().min(1).max(10_000),
            teamName: shortText,
            ownerName: shortText,
            division: z.number().int().min(1).max(12),
            wins: z.number().int().min(0).max(30),
            losses: z.number().int().min(0).max(30),
            pointsFor: boundedNumber,
            leagueId: shortText,
          })
          .strict(),
      )
      .min(1)
      .max(12),
    matchups: z
      .array(
        z
          .object({
            matchupId: z.number().int().min(1).max(10_000),
            team1RosterId: z.number().int().min(1).max(10_000),
            team2RosterId: z.number().int().min(1).max(10_000),
            team1Name: shortText,
            team2Name: shortText,
          })
          .strict(),
      )
      .min(1)
      .max(6),
  })
  .strict()
  .superRefine((body, context) => {
    const leagueIds = new Set(body.standings.map(standing => standing.leagueId));
    if (leagueIds.size !== 1) {
      context.addIssue({
        code: 'custom',
        message: 'Standings must belong to one league',
        path: ['standings'],
      });
    }

    const standingsByRoster = new Map<number, (typeof body.standings)[number]>();
    for (const [index, standing] of body.standings.entries()) {
      if (standingsByRoster.has(standing.rosterId)) {
        context.addIssue({
          code: 'custom',
          message: 'Roster IDs must be unique within the league',
          path: ['standings', index, 'rosterId'],
        });
      }
      standingsByRoster.set(standing.rosterId, standing);
    }

    const targetStandings = body.standings.filter(standing => standing.teamName === body.teamName);
    const target = targetStandings[0];
    if (
      targetStandings.length !== 1 ||
      !target ||
      target.ownerName !== body.ownerName ||
      `${target.wins}-${target.losses}` !== body.currentRecord ||
      target.pointsFor !== body.currentPoints ||
      target.division !== body.division
    ) {
      context.addIssue({
        code: 'custom',
        message: 'Target team must match one standings entry',
        path: ['teamName'],
      });
    }

    const seenRosterIds = new Set<number>();
    const seenMatchupIds = new Set<number>();
    for (const [index, matchup] of body.matchups.entries()) {
      const team1 = standingsByRoster.get(matchup.team1RosterId);
      const team2 = standingsByRoster.get(matchup.team2RosterId);
      if (
        !team1 ||
        !team2 ||
        team1.teamName !== matchup.team1Name ||
        team2.teamName !== matchup.team2Name ||
        matchup.team1RosterId === matchup.team2RosterId ||
        seenRosterIds.has(matchup.team1RosterId) ||
        seenRosterIds.has(matchup.team2RosterId) ||
        seenMatchupIds.has(matchup.matchupId)
      ) {
        context.addIssue({
          code: 'custom',
          message: 'Matchups must reference unique standings teams in the same league',
          path: ['matchups', index],
        });
      }
      seenRosterIds.add(matchup.team1RosterId);
      seenRosterIds.add(matchup.team2RosterId);
      seenMatchupIds.add(matchup.matchupId);
    }

    if (target && !seenRosterIds.has(target.rosterId)) {
      context.addIssue({
        code: 'custom',
        message: 'Target team must appear in exactly one matchup',
        path: ['matchups'],
      });
    }
  });

export const POST = async (request: NextRequest) => {
  const authorization = authorizeBearer(
    request.headers.get('authorization'),
    process.env.AI_SUMMARIZE_SECRET,
  );
  if (authorization === 'misconfigured') {
    return NextResponse.json({ error: 'AI summarization unavailable' }, { status: 503 });
  }
  if (authorization === 'unauthorized') {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const contentLength = Number(request.headers.get('content-length'));
  if (Number.isFinite(contentLength) && contentLength > MAX_REQUEST_BYTES) {
    return NextResponse.json({ error: 'Request body too large' }, { status: 413 });
  }

  if (!request.headers.get('content-type')?.toLowerCase().startsWith('application/json')) {
    return NextResponse.json({ error: 'JSON request body required' }, { status: 415 });
  }

  try {
    const boundedBody = await readBoundedBody(request.body, MAX_REQUEST_BYTES);
    if (boundedBody.status === 'too-large') {
      return NextResponse.json({ error: 'Request body too large' }, { status: 413 });
    }

    let parsedJson: unknown;
    try {
      parsedJson = JSON.parse(boundedBody.text);
    } catch {
      return NextResponse.json({ error: 'Invalid JSON request body' }, { status: 400 });
    }
    const parsedBody = requestBodySchema.safeParse(parsedJson);
    if (!parsedBody.success) {
      return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
    }

    if (!requestGate.allow('global')) {
      return NextResponse.json(
        { error: 'Too many summarization requests' },
        { status: 429, headers: { 'retry-after': '60' } },
      );
    }

    const summary = await generateTeamScenarioSummary(parsedBody.data);

    return NextResponse.json(summary);
  } catch {
    console.error('Scenario summary request failed');
    return NextResponse.json({ error: 'Failed to generate summary' }, { status: 500 });
  }
};
