/**
 * API Route: Generate AI summaries for playoff scenarios
 *
 * POST /api/playoff-scenarios/summarize
 *
 * Takes standings, matchups, and scenarios data and returns
 * human-readable summaries generated by Gemini.
 */

import { NextRequest, NextResponse } from 'next/server';
import type { TeamStanding, Week14Matchup, SeedScenario } from '@/features/playoffs/types';
import {
  generateTeamScenarioSummary,
  ScenarioSummaryInput,
} from '@/features/playoffs/simulations/scenario-summarizer';

interface RequestBody {
  teamName: string;
  ownerName: string;
  currentRecord: string;
  currentPoints: number;
  division: number;
  scenarios: SeedScenario[];
  standings: TeamStanding[];
  matchups: Week14Matchup[];
}

export async function POST(request: NextRequest) {
  try {
    const body: RequestBody = await request.json();

    // Validate required fields
    if (!body.teamName || !body.standings || !body.matchups || !body.scenarios) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const input: ScenarioSummaryInput = {
      teamName: body.teamName,
      ownerName: body.ownerName,
      currentRecord: body.currentRecord,
      currentPoints: body.currentPoints,
      division: body.division,
      scenarios: body.scenarios,
      standings: body.standings,
      matchups: body.matchups,
    };

    const summary = await generateTeamScenarioSummary(input);

    return NextResponse.json(summary);
  } catch (error) {
    console.error('Error generating scenario summary:', error);
    return NextResponse.json({ error: 'Failed to generate summary' }, { status: 500 });
  }
}
