/**
 * Static report data - no database needed!
 * Import your weekly reports as JSON and serve them statically
 */

// Example report structure
export interface WeeklyReport {
  week: number;
  season: number;
  generated: string;
  highlights: string[];
  powerRankings: Array<{
    rank: number;
    teamName: string;
    record: string;
    pointsFor: number;
    movement: number;
  }>;
  matchupResults: Array<{
    winner: string;
    loser: string;
    score: string;
    upset: boolean;
  }>;
  playerPerformances: Array<{
    player: string;
    team: string;
    points: number;
    performance: 'boom' | 'bust' | 'normal';
  }>;
}

// Import your pre-generated reports
// These can be generated by your backend scripts and committed to the repo
// import week1_2025 from '@/data/reports/2025/week1.json';
// import week2_2025 from '@/data/reports/2025/week2.json';
// ... etc

// Store all reports in a map for easy access
const REPORTS = new Map<string, WeeklyReport>([
  // ['2025-1', week1_2025 as WeeklyReport],
  // ['2025-2', week2_2025 as WeeklyReport],
  // Add more as they're generated
]);

/**
 * Get a specific weekly report
 */
export function getWeeklyReport(season: number, week: number): WeeklyReport | null {
  return REPORTS.get(`${season}-${week}`) || null;
}

/**
 * Get all reports for a season
 */
export function getSeasonReports(season: number): WeeklyReport[] {
  return Array.from(REPORTS.entries())
    .filter(([key]) => key.startsWith(`${season}-`))
    .map(([, report]) => report)
    .sort((a, b) => a.week - b.week);
}

/**
 * Get latest report
 */
export function getLatestReport(): WeeklyReport | null {
  const sorted = Array.from(REPORTS.values()).sort((a, b) => {
    if (a.season !== b.season) return b.season - a.season;
    return b.week - a.week;
  });
  return sorted[0] || null;
}

/**
 * Check if a report exists
 */
export function hasReport(season: number, week: number): boolean {
  return REPORTS.has(`${season}-${week}`);
}
