# This workflow is currently disabled
# Uncomment the lines below to re-enable it

# name: Update Fantasy Data
# on:
#   schedule:
#     # Update stats every 6 hours during NFL season
#     - cron: '0 */6 * * *'
#     # Run simulations every Monday at 8 AM
#     - cron: '0 8 * * 1'
#   # Allow manual triggers
#   workflow_dispatch:
# jobs:
#   update-data:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Update League Data
#         run: |
#           curl -X POST ${{ secrets.API_BASE_URL }}/api/update-leagues \
#             -H "Authorization: Bearer ${{ secrets.API_SECRET }}" \
#             || echo "League update failed, continuing..."
#       
#       - name: Update Player Stats
#         run: |
#           curl -X POST ${{ secrets.API_BASE_URL }}/api/update-stats \
#             -H "Authorization: Bearer ${{ secrets.API_SECRET }}" \
#             || echo "Stats update failed, continuing..."
#       
#       - name: Run Simulations (Monday only)
#         if: contains(github.event.schedule, '0 8 * * 1')
#         run: |
#           curl -X POST ${{ secrets.API_BASE_URL }}/api/run-simulations \
#             -H "Authorization: Bearer ${{ secrets.API_SECRET }}" \
#             || echo "Simulation failed, continuing..." 